PRAGMA foreign_keys=ON;
PRAGMA journal_mode=WAL;
PRAGMA busy_timeout=5000;
BEGIN IMMEDIATE;
CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY,applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,access_subject TEXT NOT NULL UNIQUE,email TEXT NOT NULL COLLATE NOCASE UNIQUE,display_name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('owner','admin','user')),status TEXT NOT NULL CHECK(status IN ('active','disabled')) DEFAULT 'active',security_version INTEGER NOT NULL DEFAULT 1 CHECK(security_version>0),created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_login_at TEXT);
CREATE TABLE IF NOT EXISTS service_accounts(id TEXT PRIMARY KEY,owner_user_id TEXT NOT NULL REFERENCES users(id),name TEXT NOT NULL,client_type TEXT NOT NULL CHECK(client_type IN ('codex','claude-code','mcp','ci','generic')),status TEXT NOT NULL CHECK(status IN ('active','disabled')) DEFAULT 'active',security_version INTEGER NOT NULL DEFAULT 1 CHECK(security_version>0),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(owner_user_id,name));
CREATE TABLE IF NOT EXISTS api_keys(id TEXT PRIMARY KEY,service_account_id TEXT NOT NULL REFERENCES service_accounts(id),name TEXT NOT NULL,prefix TEXT NOT NULL UNIQUE,secret_hash TEXT NOT NULL,pepper_id TEXT NOT NULL,scopes_json TEXT NOT NULL,expires_at TEXT,last_used_at TEXT,revoked_at TEXT,created_at TEXT NOT NULL,created_by TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),service_account_id TEXT NOT NULL REFERENCES service_accounts(id),api_key_id TEXT NOT NULL REFERENCES api_keys(id),status TEXT NOT NULL CHECK(status IN ('reserved','uploading','queued','validating','running','succeeded','failed','timeout','canceled','rejected','deleting','deleted','expired')),renderer_version TEXT NOT NULL,source_size INTEGER NOT NULL CHECK(source_size>=0),source_sha256 TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,queued_at TEXT,started_at TEXT,completed_at TEXT,exit_code INTEGER,error_code TEXT,error_message TEXT,output_size INTEGER CHECK(output_size IS NULL OR output_size>=0),cancel_requested_at TEXT,retry_of_job_id TEXT REFERENCES jobs(id),lease_owner TEXT,lease_expires_at TEXT,heartbeat_at TEXT,deleted_at TEXT);
CREATE TABLE IF NOT EXISTS artifacts(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES jobs(id),type TEXT NOT NULL CHECK(type IN ('source','pdf','log','errors','dependencies','preview')),relative_path TEXT NOT NULL,size INTEGER NOT NULL CHECK(size>=0),sha256 TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(job_id,relative_path));
CREATE TABLE IF NOT EXISTS used_nonces(nonce TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES jobs(id),state TEXT NOT NULL CHECK(state IN ('unused','claimed','consumed','released','expired')),claim_owner TEXT,claimed_at TEXT,used_at TEXT,expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS revoked_tickets(selector_type TEXT NOT NULL CHECK(selector_type IN ('jti','kid')),selector_value TEXT NOT NULL,reason TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(selector_type,selector_value));
CREATE TABLE IF NOT EXISTS idempotency_records(actor_type TEXT NOT NULL,actor_id TEXT NOT NULL,operation TEXT NOT NULL,key_hash TEXT NOT NULL,request_hash TEXT NOT NULL,resource_id TEXT,response_code INTEGER,response_json TEXT,expires_at TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(actor_type,actor_id,operation,key_hash));
CREATE TABLE IF NOT EXISTS artifact_download_leases(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES jobs(id),artifact_id TEXT NOT NULL REFERENCES artifacts(id),expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,actor_type TEXT NOT NULL,actor_id TEXT NOT NULL,action TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,result TEXT NOT NULL,ip_address TEXT,user_agent TEXT,metadata_json TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS system_settings(key TEXT PRIMARY KEY,value_json TEXT NOT NULL,updated_by TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_jobs_status_lease ON jobs(status,lease_expires_at,created_at);
CREATE INDEX IF NOT EXISTS idx_jobs_user_status ON jobs(user_id,status);
CREATE INDEX IF NOT EXISTS idx_jobs_sa_status ON jobs(service_account_id,status);
CREATE INDEX IF NOT EXISTS idx_artifacts_job ON artifacts(job_id);
CREATE INDEX IF NOT EXISTS idx_nonces_expiry ON used_nonces(state,expires_at);
CREATE INDEX IF NOT EXISTS idx_ticket_revocations_expiry ON revoked_tickets(expires_at);
CREATE INDEX IF NOT EXISTS idx_download_leases_expiry ON artifact_download_leases(expires_at);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_action_created ON audit_logs(action,created_at);
CREATE INDEX IF NOT EXISTS idx_audit_actor_created ON audit_logs(actor_type,actor_id,created_at);
CREATE INDEX IF NOT EXISTS idx_audit_target_created ON audit_logs(target_type,target_id,created_at);
CREATE INDEX IF NOT EXISTS idx_audit_result_created ON audit_logs(result,created_at);
INSERT OR IGNORE INTO schema_migrations(version,applied_at) VALUES(1,strftime('%Y-%m-%dT%H:%M:%fZ','now'));
INSERT OR IGNORE INTO system_settings(key,value_json,updated_by,updated_at) VALUES('maintenance_mode','"normal"','migration',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
COMMIT;
