import { escapeHtml } from "./templates-shared.js";

const links = [
  ["dashboard", "概要", "/admin/"],
  ["users", "ユーザー", "/admin/users/"],
  ["accounts", "クライアント", "/admin/service-accounts/"],
  ["keys", "APIキー", "/admin/api-keys/"],
  ["jobs", "ジョブ", "/admin/jobs/"],
  ["sources", "Source", "/admin/sources/"],
  ["tex", "TeX環境", "/admin/tex-environment/"],
  ["updates", "更新", "/admin/updates/"],
  ["system", "システム", "/admin/system/"],
  ["audit", "監査ログ", "/admin/audit-logs/"],
  ["docs", "API資料", "/admin/docs/"],
];

function header(page: string, controls: string): string {
  return `<header class="site-header"><strong><a href="/admin/">LaTeX Renderer 管理</a></strong><nav class="admin-nav" aria-label="管理ナビゲーション">${links.map(([id, label, url]) => `<a href="${url}"${id === page ? ' aria-current="page"' : ""}>${label}</a>`).join("")}</nav><div class="header-meta"><a class="button secondary" href="/app/">PDFに変換</a>${controls}<button type="button" class="secondary" data-theme-toggle>表示: システム</button><a class="button secondary" href="/cdn-cgi/access/logout">ログアウト</a></div></header>`;
}

export function adminPage(page: string): string {
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>管理 | LaTeX Renderer</title><link rel="stylesheet" href="/admin/assets/styles.css"><script data-cfasync="false" src="/admin/assets/site.js"></script></head><body data-page="${escapeHtml(page)}">${header(page, '<span id="identity"></span><span id="updated"></span><button type="button" id="refresh" class="secondary">更新</button>')}<main><p id="error" role="alert"></p><p id="success" role="status"></p><div id="content"><section>読み込み中</section></div></main><script data-cfasync="false" type="module" src="/admin/assets/admin.js"></script></body></html>`;
}

export function adminRenderPage(): string {
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>Webレンダリング | LaTeX Renderer 管理</title><link rel="stylesheet" href="/admin/assets/styles.css"><script data-cfasync="false" src="/admin/assets/site.js"></script></head><body>${header("render", "")}<main><div class="hero render-hero"><h1>LaTeXをPDFに変換</h1><p>TeXファイルまたはプロジェクトZIPからPDFを作成します。</p></div><section aria-labelledby="render-input-title"><h2 id="render-input-title">1. ファイルを選択</h2><form id="render-preflight" class="stack"><label class="file-picker" for="project-files"><strong>ファイルまたはZIP</strong><span>TeX、画像、参考文献、スタイルファイルなどをまとめて選択できます（最大200ファイル・20 MiB）。</span><input id="project-files" name="project" type="file" accept=".zip,.tex,.bib,.sty,.cls,.png,.jpg,.jpeg,.pdf,.eps,.svg,.bbx,.cbx,.bst,.def,.fd,.csv,.dat,application/zip" multiple></label><label class="file-picker" for="project-directory"><strong>プロジェクトフォルダー</strong><span>フォルダー構造を保ったまま選択します。</span><input id="project-directory" name="directory" type="file" webkitdirectory multiple></label><div class="actions"><button id="inspect-files" type="submit" disabled>内容を確認</button></div></form><p id="render-error" role="alert"></p><p id="render-status" role="status" aria-live="polite"></p></section><section id="render-summary" hidden aria-labelledby="render-summary-title"><h2 id="render-summary-title">2. レンダリング対象</h2><div id="render-selection" class="stack"></div><form id="render-start" class="stack"><label for="render-target"><strong>実行先</strong><select id="render-target" name="render-target" required><option value="">読み込み中…</option></select></label><label><input id="render-svg" name="render-svg" type="checkbox"> 数式とTikZをSVGでも出力</label><div class="actions"><button id="start-render" type="submit" disabled>選択した文書を開始</button><button id="create-source-ref" class="secondary" type="button" disabled>Remote MCP用参照を作成</button></div><output id="source-ref-output" class="stack" aria-live="polite"></output></form></section><section id="render-batch" hidden aria-labelledby="render-batch-title"><h2 id="render-batch-title">3. 処理状況</h2><div id="render-batch-summary" class="summary-grid" aria-live="polite"></div><div class="table-wrap"><table><thead><tr><th>文書</th><th>状態</th><th>ジョブID</th><th>操作</th></tr></thead><tbody id="render-items"></tbody></table></div><div class="actions"><button id="download-successful-render" class="secondary" type="button" disabled>成功PDFをまとめてダウンロード</button><button id="retry-failed-render" class="secondary" type="button" disabled>失敗Jobだけ再実行</button><button id="cancel-all-render" class="danger" type="button">すべて中止</button></div></section></main><script data-cfasync="false" type="module" src="/admin/assets/render.js"></script></body></html>`;
}

export function adminDocsPage(): string {
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>管理API資料 | LaTeX Renderer</title><link rel="stylesheet" href="/admin/assets/styles.css"><script data-cfasync="false" src="/admin/assets/site.js"></script></head><body>${header("docs", "")}<main><div class="hero docs-hero"><p class="eyebrow">Access保護領域</p><h1>管理API資料</h1><p>Cloudflare Accessで認証された管理者向けのAPI概要です。各操作ではアプリケーション側の権限判定も行われます。</p></div><section><h2>認証</h2><p>ブラウザ操作はCloudflare Accessのアプリケーショントークンを使用します。管理CLIはAccessに加えて <code>lra_</code> 管理APIキーを送信します。VPSへメール・表示名・権限を事前登録し、初回ログイン時に検証済みJWTの <code>email</code> と <code>sub</code> claimを連携します。VPSの招待登録とCloudflare AccessのAllow policyは別の認可境界であり、両方の許可が必要です。</p><div class="actions"><a class="button secondary" href="/admin/openapi/admin.openapi.yaml" download>管理OpenAPIをダウンロード</a></div></section><section><h2>機能</h2><div class="grid"><article><h3>ユーザー</h3><p>追加、表示名・権限変更、有効化・無効化。最後の有効なownerは保護されます。</p></article><article><h3>サービスアカウント</h3><p>追加、編集、状態変更、無効化と関連APIキーの一括失効。</p></article><article><h3>APIキー</h3><p>発行、ローテーション、失効。管理スコープを含む操作はowner限定です。</p></article><article><h3>ジョブ</h3><p>詳細、キャンセル、再実行、削除、最大100件の一括削除。</p></article><article><h3>TeX環境</h3><p>TeX Live image、言語、更新、ロールバック、検証、inventoryをWeb/CLI共通APIから管理します。</p></article><article><h3>システム</h3><p>制限、メンテナンス、ワーカー状態、署名鍵失効。</p></article><article><h3>監査ログ</h3><p>操作主体、対象、結果、メタデータを確認します。</p></article></div></section><section><h2>APIキースコープ方針</h2><p>未知スコープとレンダリング・管理スコープの混在は拒否します。管理キーの発行・ローテーションはownerだけが行えます。</p><ul><li><code>render:create</code>：ジョブ作成</li><li><code>render:read:own</code>：自分のジョブ用短時間トークンの更新。このトークンで状態確認、成果物取得、中止、削除を行います。</li><li><code>admin:users:read/write</code>、<code>admin:service-accounts:read/write</code>、<code>admin:api-keys:read/write</code>、<code>admin:jobs:read/write</code>、<code>admin:system:read/write</code>、<code>admin:audit:read</code>：対応する管理操作</li><li><code>admin:*</code>：すべての管理操作。緊急用に限定します。</li></ul></section><section><h2>署名鍵ローテーション</h2><ol><li>新しい鍵IDと32バイト以上の鍵を配置する</li><li><code>TICKET_SIGNING_KID</code> を新しいIDへ変更し、internal APIとrenderer APIを再デプロイする</li><li>旧鍵を検証用ファイルとして残した状態で、管理画面から旧鍵を失効する</li><li>最長チケット30分＋時計ずれ5分が経過してから旧鍵ファイルを削除する</li></ol><p>active鍵の失効、未構成の鍵ID、35分未満の失効期限はAPIが拒否します。</p></section><section><h2>削除済みルート</h2><ul><li><code>POST /users/{id}/unlock</code> は使用せず、<code>enable</code> または <code>disable</code> を使用します。</li><li><code>DELETE /api-keys/{id}</code> は使用せず、<code>POST /api-keys/{id}/revoke</code> を使用します。</li></ul></section></main></body></html>`;
}
