export const part1 = String.raw`
const API='/admin/api/v1',page=document.body.dataset.page||'dashboard',out=document.querySelector('#content'),err=document.querySelector('#error'),ok=document.querySelector('#success'),identity=document.querySelector('#identity');let me,activeDialog=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Date(v).toLocaleString('ja-JP'):'—';
const bytes=v=>v==null?'—':v<1048576?Math.round(v/1024)+' KiB':v<1073741824?(v/1048576).toFixed(1)+' MiB':(v/1073741824).toFixed(2)+' GiB';
async function request(path,opt={}){const method=opt.method||'GET',headers={Accept:'application/json',...(opt.headers||{})};if(!['GET','HEAD'].includes(method))headers['X-CSRF-Token']='1';const r=await fetch(API+path,{credentials:'same-origin',cache:'no-store',...opt,method,headers}),text=await r.text();let value=null;try{value=text?JSON.parse(text):null}catch{throw new Error('サーバーから不正な応答が返されました。')}if(!r.ok)throw new Error((value?.error?.code?'['+value.error.code+'] ':'')+(value?.error?.message||'HTTP '+r.status));return value}
function section(title,body){return '<section><h2>'+esc(title)+'</h2>'+body+'</section>'}
function table(items,cols,actions='',select=false){if(!items.length)return '<p class="empty">データがありません。</p>';return '<div class="table-wrap"><table><thead><tr>'+(select?'<th>選択</th>':'')+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+(actions?'<th>操作</th>':'')+'</tr></thead><tbody>'+items.map(x=>'<tr>'+(select?'<td><input type="checkbox" data-select="'+esc(x.id)+'" aria-label="'+esc(x.id)+'を選択"></td>':'')+cols.map(c=>'<td>'+esc(typeof c[1]==='function'?c[1](x):x[c[1]])+'</td>').join('')+(actions?'<td class="actions-cell">'+actions(x)+'</td>':'')+'</tr>').join('')+'</tbody></table></div>'}
function bindAction(selector,fn){document.querySelectorAll(selector).forEach(b=>b.addEventListener('click',()=>{Promise.resolve(fn(b)).catch(e=>{err.textContent=e instanceof Error?e.message:String(e)})}))}
function jsonBody(value){return{headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}}
function closeAdminDialog(dialog=activeDialog){if(!dialog)return;if(activeDialog===dialog)activeDialog=null;if(dialog.open)dialog.close();else dialog.remove()}
function openAdminDialog(title,body,{description='',wide=false}={}){closeAdminDialog();const trigger=document.activeElement instanceof HTMLElement?document.activeElement:null,d=document.createElement('dialog'),heading='dialog-title-'+crypto.randomUUID();d.className='admin-dialog'+(wide?' wide':'');d.setAttribute('aria-labelledby',heading);d.innerHTML='<div class="dialog-heading"><h2 id="'+heading+'">'+esc(title)+'</h2><button type="button" class="ghost dialog-close" aria-label="閉じる">×</button></div>'+(description?'<p class="dialog-description">'+esc(description)+'</p>':'')+body;d.querySelector('.dialog-close').onclick=()=>closeAdminDialog(d);d.addEventListener('cancel',e=>{if(d.dataset.busy==='true')e.preventDefault()});d.addEventListener('close',()=>{if(activeDialog===d)activeDialog=null;d.remove();if(trigger?.isConnected)trigger.focus()},{once:true});document.body.append(d);activeDialog=d;d.showModal();queueMicrotask(()=>{const target=d.querySelector('[autofocus],input:not([type="hidden"]),select,textarea,button');if(target instanceof HTMLElement)target.focus()});return d}
function formDialog({title,description='',fields,submitLabel='保存',danger=false,successMessage='',onSubmit,afterSuccess,wide=false,reload=true}){const d=openAdminDialog(title,'<form class="dialog-form"><div class="form-grid dialog-fields">'+fields+'</div><p class="dialog-error" role="alert"></p><div class="dialog-actions"><button type="button" class="secondary" data-dialog-cancel>キャンセル</button><button type="submit"'+(danger?' class="danger"':'')+'>'+esc(submitLabel)+'</button></div></form>',{description,wide}),form=d.querySelector('form'),localError=d.querySelector('.dialog-error');d.querySelector('[data-dialog-cancel]').onclick=()=>closeAdminDialog(d);form.onsubmit=async e=>{e.preventDefault();localError.textContent='';d.dataset.busy='true';for(const button of form.querySelectorAll('button'))button.disabled=true;try{const value=await onSubmit(new FormData(form),d);closeAdminDialog(d);if(reload)await load();if(successMessage)ok.textContent=successMessage;if(afterSuccess)afterSuccess(value)}catch(error){d.dataset.busy='false';localError.textContent=error instanceof Error?error.message:String(error);for(const button of form.querySelectorAll('button'))button.disabled=false}};return d}
function confirmDialog({title,description='',summary='',submitLabel='実行',danger=false,successMessage='',onSubmit,afterSuccess,reload=true}){return formDialog({title,description,fields:'<div class="wide dialog-summary">'+summary+'</div>',submitLabel,danger,successMessage,onSubmit,afterSuccess,reload})}
function linkageLabel(user){return user.access_subject?'連携済み':'初回ログイン待ち'}
function userDetails(user){return{ID:user.id,メール:user.email,表示名:user.display_name,権限:user.role,状態:user.status,連携状態:linkageLabel(user),連携日時:user.access_subject_linked_at??'未連携','Cloudflare AccessユーザーID':user.access_subject??'未連携',連携世代:user.access_subject_generation,最終ログイン:user.last_login_at??'なし'}}
function details(value,title='詳細'){const d=openAdminDialog(title,'<pre class="dialog-json"></pre><div class="dialog-actions"><button type="button" data-dialog-close>閉じる</button></div>',{wide:true});d.querySelector('pre').textContent=JSON.stringify(value,null,2);d.querySelector('[data-dialog-close]').onclick=()=>closeAdminDialog(d);return d}
function credentialDialog(value,title='APIキーを発行しました'){const d=openAdminDialog(title,'<div class="credential"><strong>今回だけ表示:</strong><br><code></code></div><p class="dialog-error" role="alert"></p><div class="dialog-actions"><button type="button" id="copy-issued">コピーして閉じる</button><button type="button" class="secondary" id="dismiss-issued">表示を破棄</button></div>',{description:'この値は再表示できません。安全な場所へ保存してください。',wide:true}),code=d.querySelector('code'),localError=d.querySelector('.dialog-error');code.textContent=value;d.querySelector('#copy-issued').onclick=async()=>{try{await navigator.clipboard.writeText(value);sessionStorage.removeItem('issued-key');closeAdminDialog(d);ok.textContent='APIキーをコピーしました。安全に保存してください。'}catch(error){localError.textContent=error instanceof Error?error.message:String(error)}};d.querySelector('#dismiss-issued').onclick=()=>{sessionStorage.removeItem('issued-key');closeAdminDialog(d)};return d}
async function dashboard(){const[s,j,u]=await Promise.all([request('/system/status'),request('/jobs'),request('/users')]);out.innerHTML='<div class="grid"><article class="card"><h2>ユーザー</h2><p>'+u.items.length+'件</p><a href="/admin/users/">管理する</a></article><article class="card"><h2>ジョブ</h2><p>'+j.items.length+'件</p><a href="/admin/jobs/">確認する</a></article><article class="card"><h2>メンテナンス</h2><pre></pre></article></div>'+section('最近のジョブ',table(j.items.slice(0,20),[['ID','id'],['状態','status'],['作成',x=>fmt(x.created_at)]],x=>'<button class="secondary" data-detail="'+esc(x.id)+'">詳細</button>'));out.querySelector('pre').textContent=JSON.stringify(s,null,2);bindAction('[data-detail]',b=>details(j.items.find(x=>x.id===b.dataset.detail),'ジョブ詳細'))}
`;
