export const part4 = String.raw`
async function system(){
  const[s,c,keys]=await Promise.all([request('/system/status'),request('/system/config'),request('/system/ticket-keys')]),values=Object.fromEntries(c.items.map(x=>[x.key,JSON.parse(x.value_json)])),configs=[{key:'max_queue_length',label:'最大キュー長',display:String(values.max_queue_length||100),value:values.max_queue_length||100,min:1,max:10000,mul:1,unit:''},{key:'max_user_storage_bytes',label:'利用者ごとの保存容量',display:Math.round((values.max_user_storage_bytes||1073741824)/1048576)+' MiB',value:Math.round((values.max_user_storage_bytes||1073741824)/1048576),min:100,max:102400,mul:1048576,unit:'MiB'},{key:'source_orphan_retention_minutes',label:'未参照Sourceの保持時間',display:String(values.source_orphan_retention_minutes||60)+' 分',value:values.source_orphan_retention_minutes||60,min:5,max:1440,mul:1,unit:'分'}];
  const keySummary=keys.verificationKids.length?'<button id="ticket-revoke" class="danger">旧署名鍵を失効</button>':'<p class="muted">失効対象の検証用鍵はありません。</p>';
  out.innerHTML=section('状態','<pre id="system-json"></pre>')+section('設定','<p class="muted">最大キュー長は1〜10,000、利用者ごとの保存容量は100 MiB〜100 GiB、未参照Sourceの保持時間は5分〜24時間です。上限を緩める変更はownerだけが行えます。</p>'+table(configs,[['設定','label'],['現在値','display']],x=>'<button class="secondary" data-config="'+x.key+'">編集</button>'))+section('メンテナンス','<p><strong>読み取り専用:</strong> 新規処理を止め、参照を許可します。 <strong>緊急停止:</strong> すべての利用を止めます。 <strong>解除:</strong> 通常運転へ戻します。</p><div class="actions"><button data-maint="read-only">読み取り専用</button><button data-maint="lockdown" class="danger">緊急停止</button><button data-maint="normal" class="secondary">解除</button></div>')+section('ワーカー','<p class="muted">停止は新規取得を止め、ドレインは新規取得を止めて実行中処理の完了を待ち、再開は通常処理へ戻します。</p><div class="actions"><button data-worker="pause">停止</button><button data-worker="drain">ドレイン</button><button data-worker="resume">再開</button></div>')+(me.role==='owner'?section('高度な操作','<div class="notice warning"><strong>active鍵 '+esc(keys.activeKid)+' は失効できません。</strong> 新しい鍵へ切り替えて再デプロイし、旧鍵が検証用一覧へ移った後に失効します。失効情報は最長チケット30分と時計ずれ5分を超えて保持してください。</div><div class="actions">'+keySummary+'</div>'):'');
  document.querySelector('#system-json').textContent=JSON.stringify(s,null,2);
  bindAction('[data-config]',b=>{const config=configs.find(x=>x.key===b.dataset.config);formDialog({title:config.label+'を編集',description:'現在値: '+config.display,fields:'<label>新しい値'+(config.unit?'（'+config.unit+'）':'')+'<input name="value" type="number" min="'+config.min+'" max="'+config.max+'" value="'+config.value+'" required autofocus></label><label class="wide">変更理由<input name="reason" required maxlength="500"></label>',submitLabel:'設定を保存',successMessage:'設定を更新しました。',onSubmit:f=>request('/system/config',{method:'PATCH',...jsonBody({key:config.key,value:Number(f.get('value'))*config.mul,reason:f.get('reason')})})})});
  bindAction('[data-maint]',b=>{const mode=b.dataset.maint;if(mode==='normal'){confirmDialog({title:'通常運転へ戻す',summary:'<p>メンテナンス状態を解除し、新規処理を再開します。</p>',submitLabel:'通常運転へ戻す',successMessage:'メンテナンス状態を変更しました。',onSubmit:()=>request('/system/maintenance/disable',{method:'POST',...jsonBody({})})});return}const lockdown=mode==='lockdown';formDialog({title:lockdown?'緊急停止を開始':'読み取り専用を開始',description:lockdown?'すべての利用を停止します。':'新規処理を停止し、参照だけを許可します。',fields:'<div class="wide notice warning">'+(lockdown?'<strong>公開APIを含むすべての利用へ影響します。</strong>':'新規レンダリングを受け付けなくなります。')+'</div><label class="wide">開始理由<input name="reason" required maxlength="500" autofocus></label>',submitLabel:lockdown?'緊急停止':'読み取り専用を開始',danger:lockdown,successMessage:'メンテナンス状態を変更しました。',onSubmit:f=>request('/system/maintenance/enable',{method:'POST',...jsonBody({mode,reason:f.get('reason')})})})});
  bindAction('[data-worker]',b=>{const labels={pause:'停止',drain:'ドレイン',resume:'再開'},label=labels[b.dataset.worker];confirmDialog({title:'ワーカーを'+label,summary:'<p>ワーカーの実行状態を「'+label+'」へ変更します。</p>',submitLabel:label,danger:b.dataset.worker==='pause',successMessage:'ワーカー状態を変更しました。',onSubmit:()=>request('/worker/'+b.dataset.worker,{method:'POST',...jsonBody({})})})});
  const ticketButton=document.querySelector('#ticket-revoke');if(ticketButton)ticketButton.onclick=()=>{const expiryDate=new Date(Date.now()+86400000),defaultExpiry=new Date(expiryDate.getTime()-expiryDate.getTimezoneOffset()*60000).toISOString().slice(0,16),options=keys.verificationKids.map(k=>'<option value="'+esc(k)+'">'+esc(k)+'</option>').join('');formDialog({title:'旧署名鍵を失効',description:'active鍵 '+keys.activeKid+' は選択できません。',fields:'<div class="wide notice warning"><strong>既存トークンへ影響する操作です。</strong> 失効情報は35分以上保持してください。</div><label>旧鍵ID<select name="kid" autofocus>'+options+'</select></label><label>失効情報の有効期限<input name="expiresAt" type="datetime-local" value="'+defaultExpiry+'" required></label><label class="wide">理由<input name="reason" required maxlength="500"></label>',submitLabel:'旧署名鍵を失効',danger:true,successMessage:'署名鍵を失効しました。',onSubmit:f=>request('/system/ticket-keys/'+encodeURIComponent(String(f.get('kid')))+'/revoke',{method:'POST',...jsonBody({reason:f.get('reason'),expiresAt:new Date(String(f.get('expiresAt'))).toISOString()})})})}
}

async function audit(){
  out.innerHTML=section('絞り込み','<form id="audit-filter" class="form-grid"><label>操作<input name="action" placeholder="render."></label><label>実行主体<input name="actor" placeholder="user / ID"></label><label>対象<input name="target" placeholder="job / ID"></label><label>結果<select name="result"><option value="">すべて</option><option value="success">success</option><option value="failure">failure</option><option value="requested">requested</option><option value="failed">failed</option><option value="rejected">rejected</option></select></label><label>開始日時<input name="from" type="datetime-local"></label><label>終了日時<input name="to" type="datetime-local"></label><button>検索</button><button type="reset" class="secondary">解除</button></form>')+section('監査ログ','<div id="audit-table"></div>');
  const form=document.querySelector('#audit-filter');let page=1;
  const render=async()=>{const f=new FormData(form),q=new URLSearchParams({page:String(page),pageSize:'50'});for(const key of['action','actor','target','result']){const value=String(f.get(key)||'').trim();if(value)q.set(key,value)}for(const key of['from','to']){const value=f.get(key);if(value)q.set(key,new Date(String(value)).toISOString())}const d=await request('/audit-logs?'+q),items=d.items,first=d.total===0?0:(d.page-1)*d.pageSize+1,last=Math.min(d.page*d.pageSize,d.total);document.querySelector('#audit-table').innerHTML='<p class="muted">'+first+'〜'+last+' / '+d.total+'件</p>'+table(items,[['日時',x=>fmt(x.created_at)],['主体',x=>x.actor_type+' / '+x.actor_id],['操作','action'],['対象',x=>x.target_type+' / '+x.target_id],['結果','result']],x=>'<button class="secondary" data-log="'+esc(x.id)+'">詳細</button><button class="secondary" data-copy-log="'+esc(x.target_id)+'">対象IDをコピー</button>')+'<div class="actions"><button id="audit-prev" class="secondary"'+(d.page<=1?' disabled':'')+'>前へ</button><span>'+d.page+' / '+Math.max(d.totalPages,1)+'ページ</span><button id="audit-next" class="secondary"'+(d.page>=d.totalPages?' disabled':'')+'>次へ</button></div>';bindAction('[data-log]',b=>details(items.find(x=>x.id===b.dataset.log),'監査ログ詳細'));document.querySelectorAll('[data-copy-log]').forEach(b=>b.addEventListener('click',async()=>{await navigator.clipboard.writeText(b.dataset.copyLog);ok.textContent='対象IDをコピーしました。'}));document.querySelector('#audit-prev').onclick=()=>{page--;render().catch(e=>{err.textContent=e.message})};document.querySelector('#audit-next').onclick=()=>{page++;render().catch(e=>{err.textContent=e.message})}};
  form.onsubmit=e=>{e.preventDefault();page=1;render().catch(e=>{err.textContent=e instanceof Error?e.message:String(e)})};form.onreset=()=>setTimeout(()=>{page=1;render().catch(e=>{err.textContent=e instanceof Error?e.message:String(e)})});await render()
}

async function establishSession(){const r=await fetch('/auth/session',{credentials:'same-origin',cache:'no-store'});if(r.status===401){location.replace('/login/?return_to='+encodeURIComponent(location.pathname+location.search));return false}const session=await r.json();if(!r.ok)throw new Error((session?.error?.code?'['+session.error.code+'] ':'')+(session?.error?.message||'ログインできません。'));csrfToken=session.csrfToken;authMode=session.authMode;return true}
async function load(){err.textContent='';try{if(!await establishSession())return;me=await request('/me');identity.textContent=(me.displayName?me.displayName+' / ':'')+me.role;if(page==='users')await users();else if(page==='accounts')await accounts();else if(page==='keys')await keys();else if(page==='jobs')await jobs();else if(page==='sources')await sources();else if(page==='tex')await texEnvironment();else if(page==='updates')await updates();else if(page==='system')await system();else if(page==='audit')await audit();else await dashboard();document.querySelector('#updated').textContent='更新 '+new Date().toLocaleTimeString('ja-JP')}catch(e){err.textContent=e instanceof Error?e.message:String(e)}}
document.querySelector('#logout')?.addEventListener('click',async()=>{await fetch('/auth/logout',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':csrfToken}});location.replace('/login/')});
document.querySelector('#refresh').onclick=()=>{ok.textContent='';closeAdminDialog();load()};await load();
`;
