export const part2 = String.raw`
async function users(){
  out.replaceChildren();
  const response=await fetch('/auth/config',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw new Error('ログイン方式の設定を取得できません。');const config=normalizeBrowserLoginConfiguration(await response.json()),passwordEnabled=config.methods.some(method=>method.id==='password'),oidc=config.methods.find(method=>method.id==='oidc'),authenticationOptions=[...(passwordEnabled?[{type:'password',label:'パスワード'}]:[]),...(config.backend==='cloudflare-access'||oidc?[{type:'external',label:oidc?.displayName||'Cloudflare Access'}]:[])];
  const params=new URLSearchParams(location.search),api=new URLSearchParams(),query=params.get('query')||'';if(query)api.set('query',query);if(params.get('cursor'))api.set('cursor',params.get('cursor'));const d=await request('/users'+(api.size?'?'+api:''));
  out.innerHTML=section('ユーザー','<div class="actions"><button id="user-create">ユーザーを作成</button></div><div class="notice">認証identityはメールではなく、外部providerのissuer＋subjectまたはローカルのログイン名で明示的に登録します。</div>'+table(d.items,[['メール',x=>x.email??'—'],['表示名','display_name'],['権限','role'],['状態','status'],['認証',x=>linkageLabel(x)],['最終ログイン',x=>fmt(x.last_login_at)]],x=>'<button class="secondary" data-u-detail="'+esc(x.id)+'">詳細</button><button class="secondary" data-u-edit="'+esc(x.id)+'">編集</button>'+((x.role!=='owner'||me.role==='owner')?'<button class="'+(x.status==='active'?'danger':'secondary')+'" data-u-status="'+esc(x.id)+'" data-active="'+(x.status==='active')+'">'+(x.status==='active'?'無効化':'有効化')+'</button>':'')+(me.role==='owner'&&x.identities?.length?'<button class="danger" data-u-unlink="'+esc(x.id)+'">identityを解除</button>':'')+(me.role==='owner'&&passwordEnabled?'<button class="secondary" data-u-password="'+esc(x.id)+'">パスワード変更</button>':''))+nextPage(d.nextCursor));
  document.querySelector('#user-create').onclick=()=>{
    const authFields=type=>type==='password'?'<label>ログイン名<input name="loginName" required pattern="[a-z0-9][a-z0-9._-]{2,63}" autocomplete="off"></label><label>初期パスワード<input name="password" type="password" required minlength="12" maxlength="1024" autocomplete="new-password"></label>':'<label class="wide">外部identityのsubject<input name="subject" required maxlength="500" autocomplete="off"></label><label>provider上のユーザー名（任意）<input name="preferredUsername" maxlength="500"></label>';
    const choice=authenticationOptions.length>1?'<label>認証方式<select name="authenticationType">'+authenticationOptions.map(option=>'<option value="'+option.type+'">'+esc(option.label)+'</option>').join('')+'</select></label>':'';
    const dialog=formDialog({title:'ユーザーを作成',description:'認証情報を明示的に登録します。メールと表示名は認証キーではありません。',fields:'<label>メール（任意）<input name="email" type="email" maxlength="320" autofocus></label><label>表示名<input name="displayName" required maxlength="200"></label><label>権限<select name="role"><option value="user">user</option><option value="admin">admin</option>'+(me.role==='owner'?'<option value="owner">owner</option>':'')+'</select></label>'+choice+'<div class="wide form-grid" data-auth-fields>'+authFields(authenticationOptions[0].type)+'</div><div class="wide notice warning" data-owner-warning hidden>ownerは全管理操作を実行できます。登録前に対象を再確認してください。</div>',submitLabel:'作成',successMessage:'ユーザーを作成しました。',onSubmit:f=>{
      const type=String(f.get('authenticationType')||authenticationOptions[0].type);if(!authenticationOptions.some(option=>option.type===type))throw new Error('有効な認証方式を選択してください。');
      const email=String(f.get('email')||'').trim()||null,authentication=type==='password'?{type:'password',loginName:String(f.get('loginName')),password:String(f.get('password'))}:{type:'external',subject:String(f.get('subject')),preferredUsername:String(f.get('preferredUsername')||'')||undefined};
      return request('/users',{method:'POST',...jsonBody({email,displayName:String(f.get('displayName')),role:String(f.get('role')),authentication})});
    }}),role=dialog.querySelector('[name="role"]'),warning=dialog.querySelector('[data-owner-warning]'),selector=dialog.querySelector('[name="authenticationType"]');
    if(selector)selector.onchange=()=>{dialog.querySelector('[data-auth-fields]').innerHTML=authFields(selector.value)};
    role.onchange=()=>{warning.hidden=role.value!=='owner'};role.onchange();
  };
  bindAction('[data-u-detail]',b=>details(userDetails(d.items.find(x=>x.id===b.dataset.uDetail)),'ユーザー詳細'));
  bindAction('[data-u-edit]',b=>{const x=d.items.find(v=>v.id===b.dataset.uEdit),roleField=me.role==='owner'?'<label>権限<select name="role"><option value="user"'+(x.role==='user'?' selected':'')+'>user</option><option value="admin"'+(x.role==='admin'?' selected':'')+'>admin</option><option value="owner"'+(x.role==='owner'?' selected':'')+'>owner</option></select></label>':'',dialog=formDialog({title:'ユーザーを編集',description:(x.email??'メール未設定')+' / '+x.id,fields:'<label>メール（任意）<input name="email" type="email" maxlength="320" value="'+esc(x.email??'')+'"></label><label>表示名<input name="displayName" required maxlength="200" value="'+esc(x.display_name)+'" autofocus></label>'+roleField+'<div class="wide notice warning" data-role-warning hidden></div>',submitLabel:'変更を保存',successMessage:'ユーザーを更新しました。',onSubmit:f=>{const body={email:String(f.get('email')||'').trim()||null,displayName:String(f.get('displayName'))};if(me.role==='owner')body.role=String(f.get('role'));return request('/users/'+x.id,{method:'PATCH',...jsonBody(body)})}}),role=dialog.querySelector('[name="role"]'),warning=dialog.querySelector('[data-role-warning]');if(role){role.onchange=()=>{const changed=role.value!==x.role;warning.hidden=!changed;warning.textContent=changed?'権限を '+x.role+' から '+role.value+' へ変更します。':''};role.onchange()}else warning.remove()});
  bindAction('[data-u-status]',b=>{const x=d.items.find(v=>v.id===b.dataset.uStatus),action=b.dataset.active==='true'?'disable':'enable',self=x.id===me.userId&&action==='disable',verb=action==='disable'?'無効化':'有効化';confirmDialog({title:'ユーザーを'+verb,description:x.display_name+' / '+x.email,summary:(self?'<div class="notice warning"><strong>自分自身を無効化します。</strong> 実行後はこの管理画面を利用できません。</div>':'')+'<p>対象ユーザーを'+verb+'します。</p>',submitLabel:verb,danger:action==='disable',successMessage:'ユーザー状態を変更しました。',onSubmit:()=>request('/users/'+x.id+'/'+action,{method:'POST',...jsonBody({})})})});
  bindAction('[data-u-unlink]',b=>{const x=d.items.find(v=>v.id===b.dataset.uUnlink),linked=x.identities[0];formDialog({title:'外部identityを解除',description:x.display_name+' / '+(x.email??x.id),fields:'<div class="wide notice warning"><strong>このidentityではログインできなくなり、既存セッションも失効します。</strong> メールによる自動再連携は行いません。</div><label class="wide">解除理由<textarea name="reason" required minlength="1" maxlength="500" autofocus></textarea><small>JWT、OTP、APIキーなどの秘密値は入力しないでください。</small></label><label class="wide check"><input type="checkbox" name="confirm" required> 影響を確認しました</label>',submitLabel:'identityを解除',danger:true,successMessage:'identityを解除しました。',onSubmit:f=>request('/users/'+x.id+'/identities/'+linked.id+'/unlink',{method:'POST',...jsonBody({reason:String(f.get('reason')).trim()})})})});
  bindAction('[data-u-password]',b=>{const x=d.items.find(v=>v.id===b.dataset.uPassword);formDialog({title:'パスワードを変更',description:x.display_name+' / '+x.id,fields:'<label>ログイン名<input name="loginName" required pattern="[a-z0-9][a-z0-9._-]{2,63}" value="'+esc(x.credential?.login_name??'')+'"></label><label>新しいパスワード<input name="password" type="password" required minlength="12" maxlength="1024" autocomplete="new-password"></label><label class="wide">理由<input name="reason" required maxlength="500"></label>',submitLabel:'変更',danger:true,successMessage:'パスワードとセッションを更新しました。',onSubmit:f=>request('/users/'+x.id+'/password',{method:'POST',...jsonBody({loginName:String(f.get('loginName')),password:String(f.get('password')),reason:String(f.get('reason'))})})})})
}

async function accounts(){
  const params=new URLSearchParams(location.search),accountApi=new URLSearchParams();if(params.get('cursor'))accountApi.set('cursor',params.get('cursor'));const[a,u,k]=await Promise.all([request('/service-accounts'+(accountApi.size?'?'+accountApi:'')),request('/users'),request('/api-keys')]);
  const ownerOptions=u.items.filter(x=>x.status==='active').map(x=>'<option value="'+esc(x.id)+'">'+esc(x.display_name+' ('+x.email+')')+'</option>').join(''),typeOptions=(selected='')=>[['codex','Codex'],['claude-code','Claude Code'],['mcp','MCP'],['ci','CI'],['generic','汎用CLI']].map(([value,label])=>'<option value="'+value+'"'+(selected===value?' selected':'')+'>'+label+'</option>').join('');
  out.innerHTML=section('サービスアカウント','<div class="actions"><button id="account-create">サービスアカウントを作成</button></div>'+table(a.items,[['名前','name'],['種類','client_type'],['所有者','owner_user_id'],['状態','status']],x=>'<button class="secondary" data-a-detail="'+esc(x.id)+'">詳細</button><button class="secondary" data-a-edit="'+esc(x.id)+'">編集</button><a class="button secondary" href="/admin/api-keys/?account='+encodeURIComponent(x.id)+'">APIキーを追加</a><button class="secondary" data-a-status="'+esc(x.id)+'" data-active="'+(x.status==='active')+'">'+(x.status==='active'?'無効化':'有効化')+'</button>'+(x.status==='active'?'<button class="danger" data-a-delete="'+esc(x.id)+'">無効化＋全キー失効</button>':''))+nextPage(a.nextCursor));
  document.querySelector('#account-create').onclick=()=>formDialog({title:'サービスアカウントを作成',fields:'<label>所有者<select name="ownerUserId" autofocus>'+ownerOptions+'</select></label><label>名前<input name="name" required maxlength="100"></label><label>種類<select name="clientType">'+typeOptions()+'</select></label>',submitLabel:'作成',successMessage:'サービスアカウントを作成しました。',onSubmit:f=>request('/service-accounts',{method:'POST',...jsonBody(Object.fromEntries(f))})});
  bindAction('[data-a-detail]',b=>{const x=a.items.find(v=>v.id===b.dataset.aDetail);details({...x,apiKeys:k.items.filter(v=>v.service_account_id===x.id)},'サービスアカウント詳細')});
  bindAction('[data-a-edit]',b=>{const x=a.items.find(v=>v.id===b.dataset.aEdit);formDialog({title:'サービスアカウントを編集',description:x.id,fields:'<label>名前<input name="name" required maxlength="100" value="'+esc(x.name)+'" autofocus></label><label>種類<select name="clientType">'+typeOptions(x.client_type)+'</select></label>',submitLabel:'変更を保存',successMessage:'サービスアカウントを更新しました。',onSubmit:f=>request('/service-accounts/'+x.id,{method:'PATCH',...jsonBody({name:f.get('name'),clientType:f.get('clientType')})})})});
  bindAction('[data-a-status]',b=>{const x=a.items.find(v=>v.id===b.dataset.aStatus),action=b.dataset.active==='true'?'disable':'enable',verb=action==='disable'?'無効化':'有効化';confirmDialog({title:'サービスアカウントを'+verb,description:x.name+' / '+x.id,summary:'<p>関連APIキーは失効しません。</p>',submitLabel:verb,danger:action==='disable',successMessage:'サービスアカウント状態を変更しました。',onSubmit:()=>request('/service-accounts/'+x.id+'/'+action,{method:'POST',...jsonBody({})})})});
  bindAction('[data-a-delete]',b=>{const x=a.items.find(v=>v.id===b.dataset.aDelete),count=k.items.filter(v=>v.service_account_id===x.id&&v.revoked_at===null).length;confirmDialog({title:'無効化して全キーを失効',description:x.name+' / '+x.id,summary:'<div class="notice warning"><strong>サービスアカウントを無効化し、有効なAPIキー '+count+'件をすべて失効します。</strong></div>',submitLabel:'無効化＋全キー失効',danger:true,successMessage:'無効化とキー失効を実行しました。',onSubmit:()=>request('/service-accounts/'+x.id,{method:'DELETE'})})})
}
`;
