export const part6 = String.raw`
let texPageData=null;
function texLanguageLabel(item){return item.description||item.name||item.id}
function texSelectorDisplay(selector){if(!selector)return '未設定';if(selector.mode==='latest')return 'latest';if(selector.mode==='weekly')return 'weekly:'+selector.value;return selector.value||selector.mode}
function texRuntimeCard(value,title){if(!value)return '<article class="card"><h3>'+esc(title)+'</h3><p class="muted">なし</p></article>';const selected=value.languages||[],effective=value.effectiveLanguageCollections||selected,dependencies=effective.filter(x=>!selected.includes(x));return '<article class="card"><h3>'+esc(title)+'</h3><dl><dt>Base</dt><dd>'+esc(value.snapshotDate||texSelectorDisplay(value.selector))+'</dd><dt>Base digest</dt><dd><code>'+esc(value.baseDigest||'—')+'</code></dd><dt>Runtime</dt><dd><code>'+esc(value.runtimeImageId||'—')+'</code></dd><dt>取得元</dt><dd>'+esc(value.runtimeSource==='ghcr'?'公開GHCR Package':value.runtimeSource==='local-build'?'ローカルビルド':'—')+'</dd><dt>選択言語</dt><dd>'+esc(selected.join(', ')||'なし')+'</dd><dt>依存言語collection</dt><dd>'+esc(dependencies.join(', ')||'なし')+'</dd><dt>適用日時</dt><dd>'+esc(value.appliedAt?fmt(value.appliedAt):'—')+'</dd></dl></article>'}
function renderTexOperation(operation,reconnecting=false){const target=document.querySelector('#tex-operation');if(!target||!operation)return;const status=reconnecting?'Admin APIへ再接続中':operation.status==='running'?'処理中':operation.status==='succeeded'?'正常に完了':'失敗';let card=target.querySelector('[data-tex-operation]');if(!card||card.dataset.operationId!==operation.id){target.innerHTML='<article class="card" data-tex-operation data-operation-id="'+esc(operation.id||'')+'"><strong data-operation-status></strong><p class="muted" data-operation-label></p><details><summary>詳細ログを表示</summary><pre></pre></details></article>';card=target.querySelector('[data-tex-operation]')}card.querySelector('[data-operation-status]').textContent=status;card.querySelector('[data-operation-label]').textContent=(operation.type||'Image operation')+' / '+(operation.id||'');const pre=card.querySelector('pre'),nextLog=operation.log||'ログはまだありません。',previousScrollTop=pre.scrollTop,followTail=pre.scrollHeight-pre.scrollTop-pre.clientHeight<8;if(pre.textContent!==nextLog){pre.textContent=nextLog;pre.scrollTop=followTail?pre.scrollHeight:previousScrollTop}}
async function texEnvironment(){
  const[state,images,languages]=await Promise.all([request('/tex-environment/state'),request('/tex-environment/images'),request('/tex-environment/languages')]),desired=state.desired||{};texPageData={state,images,languages};
  const selector=desired.selector||{mode:'latest',value:null},selected=new Set(desired.languages||[]),recommended=languages.items.filter(x=>x.recommended),others=languages.items.filter(x=>!x.recommended),languageRows=items=>items.map(item=>'<label class="card" data-language-row data-label="'+esc((texLanguageLabel(item)+' '+item.id).toLowerCase())+'"><span><input type="checkbox" name="tex-language" value="'+esc(item.id)+'"'+(selected.has(item.id)?' checked':'')+'> <strong>'+esc(texLanguageLabel(item))+'</strong></span><small><code>'+esc(item.id)+'</code></small></label>').join('');
  const savedCountry=languages.countryOverride||'';
  out.innerHTML='<div class="hero"><p class="eyebrow">Image Manager</p><h1>TeX環境</h1><p>Web UIとCLIは同じ管理APIを使用します。変更はclean Baseから新しいRuntimeを作成し、検証成功後だけ切り替えます。</p></div>'+
    section('現在の状態',(state.lastApplyError?'<div class="notice warning"><strong>前回のTeX環境変更は失敗しました。現在のRuntimeは変更されていません。</strong><p>'+esc(state.lastApplyError)+'</p></div>':'')+'<div class="grid">'+texRuntimeCard(state.current,'現在のRuntime')+texRuntimeCard(state.previous,'前回の正常Runtime')+'</div><p class="muted">Image repository: <code>'+esc(images.repository||'—')+'</code>'+(images.registryUnavailable?' / Registry一覧を現在取得できません。':'')+'</p>')+
    section('Image','<form id="tex-image-form" class="form-grid"><label>選択方法<select id="tex-image-mode" name="mode"><option value="latest"'+(selector.mode==='latest'?' selected':'')+'>Latest</option><option value="date"'+(selector.mode==='date'?' selected':'')+'>日付</option><option value="weekly"'+(selector.mode==='weekly'?' selected':'')+'>Weekly</option><option value="digest"'+(selector.mode==='digest'?' selected':'')+'>Digest（高度な設定）</option></select></label><label>値<input id="tex-image-value" name="value" value="'+esc(selector.value||'')+'" list="tex-image-values" placeholder="YYYY-MM-DD / YYYY-Www / sha256:..."></label><datalist id="tex-image-values">'+(images.daily||[]).map(x=>'<option value="'+esc(x)+'"></option>').join('')+(images.weekly||[]).map(x=>'<option value="'+esc(x)+'"></option>').join('')+'</datalist><label><input id="tex-auto-update" type="checkbox"'+(desired.autoUpdate?' checked':'')+'> latestを自動追従</label><label><input id="tex-rebuild-missing" type="checkbox" checked> GHCRにない日付はこのサーバーでBaseをcold build</label><label><input id="tex-runtime-build-missing" type="checkbox"'+(desired.runtimeBuildIfMissing?' checked':'')+'> Packageにないカスタム言語Runtimeをこのサーバーでビルド</label><p class="muted wide">標準構成は公開済みRuntimeをpullします。ローカルRuntimeビルドは時間とディスク容量を使うため、カスタム言語構成で必要な場合だけ有効にしてください。</p></form>')+
    section('国と言語の並び順','<form id="tex-country-form" class="form-grid"><label>保存する国の上書き（ISO 2文字）<input name="country" maxlength="2" pattern="[A-Za-z]{2}" value="'+esc(savedCountry)+'" placeholder="JP"></label><div class="wide"><p class="muted">検出: '+esc(languages.detectedCountry||'不明')+' / 有効: '+esc(languages.effectiveCountry||'不明')+' / 保存済み上書き: '+esc(languages.countryOverride||'なし')+'。国は並び順にだけ使い、言語は自動選択しません。</p><div class="actions"><button type="submit">国を保存</button><button type="button" id="tex-country-clear" class="secondary">上書きを解除</button></div></div></form>')+
    section('言語','<div class="stack">'+(languages.catalogUnavailable?'<div class="notice warning"><strong>TeX Live言語カタログを取得できません。</strong> 現在保存済みの言語だけを表示しています。既存の選択の保持・解除はできますが、新しい言語の選択や「すべて選択」はカタログ復旧後に実行してください。</div>':'')+'<p class="muted">初期状態では何も選択されません。国に対応する言語、English、その他のアルファベット順で表示します。TeX Liveが依存として追加する言語collectionは選択状態とは分けて管理します。</p><label>検索<input id="tex-language-search" type="search" placeholder="Japanese / collection-lang..."></label><div class="actions"><button type="button" id="tex-select-all" class="secondary"'+(languages.catalogUnavailable?' disabled':'')+'>すべて選択</button><button type="button" id="tex-clear-all" class="secondary">すべて解除</button></div>'+(recommended.length?'<h3>おすすめ</h3><div class="grid" id="tex-recommended-languages">'+languageRows(recommended)+'</div>':'')+'<h3>その他</h3><div class="grid" id="tex-other-languages">'+languageRows(others)+'</div></div>')+
    section('変更','<div class="actions"><button id="tex-apply">変更を適用</button><button id="tex-refresh-latest" class="secondary">Latestを確認</button><button id="tex-rollback" class="secondary"'+(state.previous?'':' disabled')+'>前回へロールバック</button><button id="tex-revalidate" class="secondary"'+(state.current?'':' disabled')+'>再検証</button><button id="tex-cleanup" class="secondary">ローカルImageを整理</button></div><div id="tex-operation" class="stack" aria-live="polite"></div>')+
    section('Package / Font inventory','<form id="tex-inventory-form" class="form-grid"><label>種類<select name="kind"><option value="packages">Packages</option><option value="fonts">Fonts</option></select></label><label>検索<input name="query" placeholder="tikz / Noto ..."></label><button>検索</button></form><div id="tex-inventory-result"></div>');

  const mode=document.querySelector('#tex-image-mode'),value=document.querySelector('#tex-image-value'),autoUpdate=document.querySelector('#tex-auto-update');
  const syncImageInput=()=>{const m=mode.value;value.disabled=m==='latest';value.placeholder=m==='date'?'YYYY-MM-DD':m==='weekly'?'YYYY-Www':m==='digest'?'sha256:...':'';if(m==='latest')value.value='';autoUpdate.disabled=m!=='latest';if(m!=='latest')autoUpdate.checked=false};mode.onchange=syncImageInput;syncImageInput();
  document.querySelector('#tex-language-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('[data-language-row]').forEach(row=>{row.hidden=q&&!row.dataset.label.includes(q)})};
  document.querySelector('#tex-select-all').onclick=()=>{if(languages.catalogUnavailable)return;document.querySelectorAll('input[name="tex-language"]').forEach(x=>{x.checked=true})};
  document.querySelector('#tex-clear-all').onclick=()=>document.querySelectorAll('input[name="tex-language"]').forEach(x=>{x.checked=false});
  document.querySelector('#tex-country-form').onsubmit=async e=>{e.preventDefault();const raw=String(new FormData(e.target).get('country')||'').trim().toUpperCase();if(!/^[A-Z]{2}$/.test(raw)){err.textContent='国はISO 2文字で入力してください。';return}await request('/tex-environment/country',{method:'POST',...jsonBody({country:raw})});ok.textContent='国の設定を保存しました。';await texEnvironment()};
  document.querySelector('#tex-country-clear').onclick=async()=>{await request('/tex-environment/country',{method:'POST',...jsonBody({country:null})});ok.textContent='国の上書きを解除しました。';await texEnvironment()};
  document.querySelector('#tex-apply').onclick=()=>{try{const input=collectTexApply();const languageText=input.languages.length?input.languages.join(', '):'なし';confirmDialog({title:'TeX環境を変更',description:'一致する公開Runtimeを優先して取得し、検証成功後だけ切り替えます。',summary:'<dl><dt>Image</dt><dd>'+esc(texSelectorDisplay(input.selector))+'</dd><dt>言語</dt><dd>'+esc(languageText)+'</dd><dt>Latest自動追従</dt><dd>'+(input.autoUpdate?'ON':'OFF')+'</dd><dt>Runtimeローカルビルド</dt><dd>'+(input.runtimeBuildIfMissing?'Package不在時に許可':'許可しない')+'</dd></dl>',submitLabel:'取得・検証して適用',successMessage:'TeX環境の処理を開始しました。',reload:false,onSubmit:()=>request('/tex-environment/apply',{method:'POST',...jsonBody(input)}),afterSuccess:startTexOperation})}catch(e){err.textContent=e instanceof Error?e.message:String(e)}};
  for(const [id,path,title,danger] of [['tex-refresh-latest','refresh','Latestを確認',false],['tex-rollback','rollback','前回の正常Runtimeへ戻す',true],['tex-revalidate','revalidate','現在のRuntimeを再検証',false],['tex-cleanup','cleanup','未使用のローカルRuntime Imageを整理',false]]){const button=document.querySelector('#'+id);if(!button)continue;button.onclick=()=>confirmDialog({title,summary:'<p>Image Managerのallowlistされた操作を実行します。実行ログはこの画面で確認できます。</p>',submitLabel:title,danger,successMessage:'処理を開始しました。',reload:false,onSubmit:()=>request('/tex-environment/'+path,{method:'POST',...jsonBody({})}),afterSuccess:startTexOperation})}
  document.querySelector('#tex-inventory-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),kind=String(f.get('kind')),query=String(f.get('query')||'').trim(),data=await request('/tex-environment/inventory/'+kind+(query?'?q='+encodeURIComponent(query):''));document.querySelector('#tex-inventory-result').innerHTML='<p class="muted">'+data.total+'件'+(data.truncated?'（先頭500件を表示）':'')+'</p><pre></pre>';document.querySelector('#tex-inventory-result pre').textContent=data.items.join('\n')};
  const operationId=state.activeOperationId||state.lastOperationId;if(operationId){const existing=await request('/tex-environment/operations/'+encodeURIComponent(operationId)).catch(()=>null);if(existing){renderTexOperation(existing);if(existing.status==='running')watchTexOperation(existing)}}
}
function collectTexApply(){const mode=document.querySelector('#tex-image-mode').value,raw=document.querySelector('#tex-image-value').value.trim();let selector;if(mode==='latest')selector={mode:'latest',value:null};else if(mode==='date'&&/^\d{4}-\d{2}-\d{2}$/.test(raw))selector={mode,value:raw};else if(mode==='weekly'&&/^\d{4}-W\d{2}$/.test(raw))selector={mode,value:raw};else if(mode==='digest'&&/^sha256:[a-f0-9]{64}$/.test(raw))selector={mode,value:raw};else throw new Error('Image指定が正しくありません。');return{selector,languages:[...document.querySelectorAll('input[name="tex-language"]:checked')].map(x=>x.value),autoUpdate:selector.mode==='latest'&&document.querySelector('#tex-auto-update').checked,rebuildIfMissing:document.querySelector('#tex-rebuild-missing').checked,runtimeBuildIfMissing:document.querySelector('#tex-runtime-build-missing').checked}}
function startTexOperation(value){if(!value?.id)return;watchTexOperation(value)}
async function watchTexOperation(initial){let operation=initial,failures=0;for(;;){renderTexOperation(operation);if(operation.status==='succeeded'){ok.textContent='TeX環境の処理が正常に完了しました。';await texEnvironment();return}if(operation.status==='failed'){err.textContent=operation.error||'TeX環境の処理に失敗しました。';await texEnvironment();return}await new Promise(resolve=>setTimeout(resolve,1500));try{operation=await request('/tex-environment/operations/'+encodeURIComponent(operation.id));failures=0}catch(e){failures++;renderTexOperation(operation,true);if(failures>=40){err.textContent='Admin APIへの再接続に失敗しました。処理自体はImage Manager側で継続している可能性があります。';return}await new Promise(resolve=>setTimeout(resolve,1000))}}}
`;
