export const part7 = String.raw`
function updateVersion(value){return value?'v'+value:'—'}
function renderUpdateOperation(operation,reconnecting=false){
  const target=document.querySelector('#update-operation');if(!target||!operation)return;
  const status=reconnecting?'Admin APIへ再接続中':operation.status==='running'?'処理中':operation.status==='succeeded'?'正常に完了':'失敗';
  target.replaceChildren();const card=document.createElement('article');card.className='card';const strong=document.createElement('strong');strong.textContent=status;const label=document.createElement('p');label.className='muted';label.textContent=(operation.type||'update')+' / '+(operation.id||'');const details=document.createElement('details');details.open=true;const summary=document.createElement('summary');summary.textContent='詳細ログ';const pre=document.createElement('pre');pre.textContent=operation.log||'ログはまだありません。';details.append(summary,pre);card.append(strong,label,details);target.append(card)
}
async function updates(){
  const state=await request('/updates/state'),installed=state.installed||{},available=state.available||null,policy=state.policy||{channel:'stable',mode:'notify'};
  const unavailable=available&&available.unavailableReason?'<div class="notice warning"><strong>このReleaseはUpdate Managerから適用できません。</strong><p>'+esc(available.unavailableReason)+'</p></div>':'';
  const stateCards='<div class="grid"><article class="card"><h3>インストール済み</h3><p><strong>'+esc(updateVersion(installed.version))+'</strong></p><p class="muted">Release ID: <code>'+esc(installed.releaseId||'—')+'</code></p></article><article class="card"><h3>確認済みの候補</h3><p><strong>'+esc(updateVersion(available&&available.version))+'</strong></p><p class="muted">Policy: '+esc(policy.channel)+' / '+(policy.mode==='automatic'?'自動適用':'通知のみ')+'</p></article><article class="card"><h3>ロールバック</h3><p><code>'+esc(state.previousReleaseId||'前回の正常版なし')+'</code></p></article></div>';
  const policyForm='<form id="update-policy-form" class="form-grid"><label>Stable Release<select name="mode"><option value="notify"'+(policy.mode==='notify'?' selected':'')+'>確認・通知のみ（既定）</option><option value="automatic"'+(policy.mode==='automatic'?' selected':'')+'>検証後に自動適用</option></select></label><label class="wide">変更理由（監査ログに保存）<textarea name="reason" required minlength="1" maxlength="500"></textarea><small>秘密情報やAPIキーは入力しないでください。</small></label><div class="wide notice warning"><strong>自動適用は明示的なopt-inです。</strong> backup、Runtime整合、サービス再起動、health check、可能な場合のrollbackまで無人で実行します。</div><button>ポリシーを保存</button></form>';
  const operationForm='<div class="notice"><strong>初期設定後のsudo入力は不要です。</strong> Update Managerは公開リポジトリのimmutable ReleaseとGitHubのSHA-256 digestを検証し、設定・秘密情報・データをGit外に保ったまま更新します。</div><form id="update-version-form" class="form-grid"><label>Version（空欄は最新stable）<input name="version" pattern="v?(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)(?:-rc\\.[1-9]\\d*)?" placeholder="vX.Y.Z"></label><small class="wide">Release Candidateは保守検証専用です。Immutableな<code>-rc.N</code>を明示した場合だけ適用でき、自動更新では選択されません。</small><div class="actions wide"><button type="button" id="update-check" class="secondary">更新を確認</button><button type="button" id="update-apply">取得・検証して更新</button><button type="button" id="update-rollback" class="danger"'+(state.previousReleaseId&&state.previousRollbackCompatible?'':' disabled')+'>前回へロールバック</button></div></form><div id="update-operation" class="stack" aria-live="polite"></div>';
  out.innerHTML='<div class="hero"><p class="eyebrow">Immutable GitHub Release</p><h1>アプリケーション更新</h1><p>WebとCLIは同じUpdate Managerを使用します。root権限はallowlistされた取得・検証・切替・ロールバックだけに分離されています。</p></div>'+section('状態',stateCards+unavailable+(state.lastError?'<div class="notice warning"><strong>前回の更新処理は失敗しました。</strong><p>'+esc(state.lastError)+'</p></div>':''))+section('更新ポリシー',policyForm)+section('操作',operationForm);
  const version=()=>String(new FormData(document.querySelector('#update-version-form')).get('version')||'').trim();
  document.querySelector('#update-policy-form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.target),mode=String(data.get('mode')),reason=String(data.get('reason')||'').trim();await request('/updates/policy',{method:'POST',...jsonBody({channel:'stable',mode,reason})});ok.textContent='アプリケーション更新ポリシーを保存しました。';await updates()};
  document.querySelector('#update-check').onclick=async()=>{const selected=version(),result=await request('/updates/check',{method:'POST',...jsonBody(selected?{version:selected}:{})});ok.textContent=updateVersion(result.version)+'を確認しました。';await updates()};
  document.querySelector('#update-apply').onclick=()=>{const selected=version();confirmDialog({title:'アプリケーションを更新',description:'immutable Releaseを検証し、バックアップ、切替、ヘルスチェックを行います。',summary:'<p>対象: <strong>'+esc(selected||'最新stable')+'</strong></p><p>失敗時はRelease policyが許す場合に直前の正常Releaseへ戻します。</p>',reason:true,submitLabel:'更新を開始',successMessage:'更新処理を開始しました。',reload:false,onSubmit:f=>request('/updates/apply',{method:'POST',...jsonBody({...(selected?{version:selected}:{}),reason:String(f.get('reason')||'').trim()})}),afterSuccess:startUpdateOperation})};
  document.querySelector('#update-rollback').onclick=()=>confirmDialog({title:'前回のアプリケーションへ戻す',summary:'<p>現在の状態をバックアップしてから <code>'+esc(state.previousReleaseId||'')+'</code> を再デプロイします。</p>',reason:true,submitLabel:'ロールバック',danger:true,successMessage:'ロールバックを開始しました。',reload:false,onSubmit:f=>request('/updates/rollback',{method:'POST',...jsonBody({reason:String(f.get('reason')||'').trim()})}),afterSuccess:startUpdateOperation});
  const operationId=state.activeOperationId||state.lastOperationId;if(operationId){const operation=await request('/updates/operations/'+encodeURIComponent(operationId)).catch(()=>null);if(operation){renderUpdateOperation(operation);if(operation.status==='running')watchUpdateOperation(operation)}}
}
function startUpdateOperation(value){if(value&&value.id)watchUpdateOperation(value)}
async function watchUpdateOperation(initial){let operation=initial,failures=0;for(;;){renderUpdateOperation(operation);if(operation.status==='succeeded'){ok.textContent='アプリケーション更新が正常に完了しました。';await updates();return}if(operation.status==='failed'){err.textContent=operation.error||'アプリケーション更新に失敗しました。';await updates();return}await new Promise(resolve=>setTimeout(resolve,1500));try{operation=await request('/updates/operations/'+encodeURIComponent(operation.id));failures=0}catch(e){failures++;renderUpdateOperation(operation,true);if(failures>=120){err.textContent='更新後のAdmin APIへ再接続できません。CLIまたはsystemd journalでUpdate Managerの状態を確認してください。';return}await new Promise(resolve=>setTimeout(resolve,1000))}}}
`;
