export const part3 = String.raw`
async function keys(){
  const[k,a]=await Promise.all([request('/api-keys'),request('/service-accounts')]);
  const renderScopes=[['render:create','ジョブを作成'],['render:read:own','自分のジョブの状態確認、成果物取得、中止、削除に使う短時間トークンを更新']];
  const adminScopes=[['admin:users:read','ユーザー参照'],['admin:users:write','ユーザー変更'],['admin:service-accounts:read','サービスアカウント参照'],['admin:service-accounts:write','サービスアカウント変更'],['admin:api-keys:read','APIキー参照'],['admin:api-keys:write','APIキー発行・失効'],['admin:jobs:read','ジョブ参照'],['admin:jobs:write','ジョブ操作'],['admin:system:read','システム参照'],['admin:system:write','システム変更'],['admin:audit:read','監査ログ参照'],['admin:*','すべての管理操作']];
  const scopeFields=(items,kind)=>'<fieldset class="wide" data-key-kind="'+kind+'"><legend>'+ (kind==='render'?'レンダリング':'管理') +'スコープ</legend>'+items.map(([value,label])=>'<label class="check"><input type="checkbox" name="scope" value="'+value+'"'+(kind==='render'?' checked':'')+'> <code>'+value+'</code> — '+label+'</label>').join('')+'</fieldset>';
  const requestedAccount=new URLSearchParams(location.search).get('account'),accountOptions=a.items.filter(x=>x.status==='active').map(x=>'<option value="'+esc(x.id)+'"'+(x.id===requestedAccount?' selected':'')+'>'+esc(x.name)+'</option>').join('');
  out.innerHTML=section('APIキー','<div class="actions"><button id="key-create">APIキーを発行</button></div>'+table(k.items,[['Prefix','prefix'],['名前','name'],['サービスアカウント','service_account_id'],['最終利用',x=>fmt(x.last_used_at)],['失効',x=>fmt(x.revoked_at)]],x=>x.revoked_at?'':'<button class="secondary" data-k-rotate="'+esc(x.id)+'">ローテーション</button><button class="danger" data-k-revoke="'+esc(x.id)+'">失効</button>'));
  document.querySelector('#key-create').onclick=()=>{const kindField='<label>キー種別<select name="kind" id="dialog-key-kind"><option value="render">レンダリングキー</option>'+(me.role==='owner'?'<option value="admin">管理キー（owner限定）</option>':'')+'</select></label>',dialog=formDialog({title:'APIキーを発行',description:'発行したキーは結果ダイアログに一度だけ表示されます。',fields:'<label>サービスアカウント<select name="account" autofocus>'+accountOptions+'</select></label><label>名前<input name="name" required maxlength="100"></label>'+kindField+scopeFields(renderScopes,'render')+(me.role==='owner'?scopeFields(adminScopes,'admin'):'')+'<label>有効期限<input name="expiresAt" type="datetime-local"></label>',submitLabel:'発行',successMessage:'APIキーを発行しました。',wide:true,onSubmit:async f=>{const scopes=f.getAll('scope').map(String),expires=f.get('expiresAt');if(!scopes.length)throw new Error('スコープを1つ以上選択してください。');const v=await request('/service-accounts/'+f.get('account')+'/api-keys',{method:'POST',...jsonBody({name:f.get('name'),scopes,expiresAt:expires?new Date(String(expires)).toISOString():null})});sessionStorage.setItem('issued-key',v.apiKey);return v}}),kind=dialog.querySelector('#dialog-key-kind'),syncKind=()=>{for(const field of dialog.querySelectorAll('[data-key-kind]')){const active=field.dataset.keyKind===kind.value;field.hidden=!active;for(const input of field.querySelectorAll('input'))input.disabled=!active}};kind.onchange=syncKind;syncKind()};
  bindAction('[data-k-rotate]',b=>confirmDialog({title:'APIキーをローテーション',description:b.dataset.kRotate,summary:'<div class="notice warning">古いキーを失効し、新しいキーを発行します。古い値は直ちに利用できなくなります。</div>',submitLabel:'ローテーション',danger:true,successMessage:'APIキーをローテーションしました。',onSubmit:async()=>{const v=await request('/api-keys/'+b.dataset.kRotate+'/rotate',{method:'POST',...jsonBody({})});sessionStorage.setItem('issued-key',v.apiKey);return v}}));
  bindAction('[data-k-revoke]',b=>confirmDialog({title:'APIキーを失効',description:b.dataset.kRevoke,summary:'<div class="notice warning">このAPIキーを失効します。実行後は元に戻せません。</div>',submitLabel:'失効',danger:true,successMessage:'APIキーを失効しました。',onSubmit:()=>request('/api-keys/'+b.dataset.kRevoke+'/revoke',{method:'POST',...jsonBody({})})}));
  const issued=sessionStorage.getItem('issued-key');if(issued)credentialDialog(issued)
}

async function jobsLegacy(){
  const d=await request('/jobs'),active=new Set(['reserved','uploading','queued','validating','running']),retryable=new Set(['succeeded','failed','timeout','canceled','rejected']),deletable=new Set(['succeeded','failed','timeout','canceled','rejected','expired']),requestedJob=new URLSearchParams(location.search).get('job');
  out.innerHTML=section('ジョブ','<div class="actions"><a class="button" href="/admin/render/">Webでジョブを作成</a><button id="bulk-delete" class="danger">選択したジョブを削除</button><span id="selected-count">0件選択</span></div>'+table(d.items,[['ID','id'],['ユーザー','user_id'],['状態','status'],['入力',x=>bytes(x.source_size)],['作成',x=>fmt(x.created_at)]],x=>'<button class="secondary" data-j-detail="'+esc(x.id)+'">詳細</button>'+(active.has(x.status)?'<button class="secondary" data-j-cancel="'+esc(x.id)+'">中止</button>':'')+(retryable.has(x.status)?'<button class="secondary" data-j-retry="'+esc(x.id)+'">再実行</button>':'')+(deletable.has(x.status)?'<button class="danger" data-j-delete="'+esc(x.id)+'">削除</button>':''),true));
  for(const box of document.querySelectorAll('[data-select]')){const job=d.items.find(x=>x.id===box.dataset.select);box.disabled=!deletable.has(job.status);box.addEventListener('change',()=>{document.querySelector('#selected-count').textContent=document.querySelectorAll('[data-select]:checked').length+'件選択'})}
  bindAction('[data-j-detail]',async b=>details(await request('/jobs/'+b.dataset.jDetail),'ジョブ詳細'));
  bindAction('[data-j-cancel]',b=>confirmDialog({title:'ジョブを中止',description:b.dataset.jCancel,summary:'<p>実行中の場合は停止を要求します。処理状況によって完了まで時間がかかることがあります。</p>',submitLabel:'中止を要求',danger:true,successMessage:'中止を要求しました。',onSubmit:()=>request('/jobs/'+b.dataset.jCancel+'/cancel',{method:'POST',...jsonBody({})})}));
  bindAction('[data-j-retry]',b=>confirmDialog({title:'ジョブを再実行',description:b.dataset.jRetry,summary:'<p>元の入力を使って新しいジョブを作成します。</p>',submitLabel:'再実行',successMessage:'再実行ジョブを作成しました。',onSubmit:()=>request('/jobs/'+b.dataset.jRetry+'/retry',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:'{}'})}));
  bindAction('[data-j-delete]',b=>confirmDialog({title:'ジョブを削除',description:b.dataset.jDelete,summary:'<div class="notice warning">入力、PDF、ログ、プレビューを削除対象へ移します。</div>',submitLabel:'削除',danger:true,successMessage:'削除を要求しました。',onSubmit:()=>request('/jobs/'+b.dataset.jDelete,{method:'DELETE'})}));
  document.querySelector('#bulk-delete').onclick=()=>{const ids=[...document.querySelectorAll('[data-select]:checked')].map(x=>x.dataset.select).slice(0,100);if(!ids.length){err.textContent='ジョブを選択してください。';return}confirmDialog({title:'選択したジョブを一括削除',description:ids.length+'件を削除対象へ移します。',summary:'<div class="notice warning"><strong>入力と成果物を削除します。</strong></div><details><summary>対象IDを表示</summary><ul>'+ids.map(id=>'<li><code>'+esc(id)+'</code></li>').join('')+'</ul></details>',submitLabel:ids.length+'件を削除',danger:true,successMessage:'一括削除を要求しました。',onSubmit:()=>request('/jobs/bulk-delete',{method:'POST',...jsonBody({ids})})})}
  if(requestedJob&&/^job_[a-f0-9]{32}$/.test(requestedJob))details(await request('/jobs/'+requestedJob),'ジョブ詳細');
}
`;
