export const part2 = String.raw`
async function users(){
  const d=await request('/users');
  out.innerHTML=section('ユーザー','<div class="actions"><button id="user-create">管理者を招待</button></div><div class="notice">最後の有効なownerは降格・無効化できません。ownerの作成、昇格、降格はダイアログ内に影響を表示します。</div>'+table(d.items,[['メール','email'],['表示名','display_name'],['権限','role'],['状態','status'],['Access連携',x=>linkageLabel(x)],['連携日時',x=>fmt(x.access_subject_linked_at)],['最終ログイン',x=>fmt(x.last_login_at)]],x=>'<button class="secondary" data-u-detail="'+esc(x.id)+'">詳細</button><button class="secondary" data-u-edit="'+esc(x.id)+'">編集</button>'+((x.role!=='owner'||me.role==='owner')?'<button class="'+(x.status==='active'?'danger':'secondary')+'" data-u-status="'+esc(x.id)+'" data-active="'+(x.status==='active')+'">'+(x.status==='active'?'無効化':'有効化')+'</button>':'')+(me.role==='owner'&&x.access_subject?'<button class="danger" data-u-unlink="'+esc(x.id)+'">Access連携を解除</button>':'')));
  document.querySelector('#user-create').onclick=()=>{const dialog=formDialog({title:'管理者を招待',description:'メール、表示名、権限を事前登録します。本人の初回ログイン時に検証済みAccess identityを連携します。Cloudflare Access側の許可は別途必要です。',fields:'<label>メール<input name="email" type="email" required maxlength="320" autofocus></label><label>表示名<input name="displayName" required maxlength="200"></label><label>権限<select name="role"><option value="user">user</option><option value="admin">admin</option>'+(me.role==='owner'?'<option value="owner">owner</option>':'')+'</select></label><div class="wide notice warning" data-owner-warning hidden>ownerは全管理操作を実行できます。登録前に対象を再確認してください。</div>',submitLabel:'招待を登録',successMessage:'未連携ユーザーを登録しました。',onSubmit:f=>request('/users',{method:'POST',...jsonBody(Object.fromEntries(f))})}),role=dialog.querySelector('[name="role"]'),warning=dialog.querySelector('[data-owner-warning]');role.onchange=()=>{warning.hidden=role.value!=='owner'};role.onchange()};
  bindAction('[data-u-detail]',b=>details(userDetails(d.items.find(x=>x.id===b.dataset.uDetail)),'ユーザー詳細'));
  bindAction('[data-u-edit]',b=>{const x=d.items.find(v=>v.id===b.dataset.uEdit),roleField=me.role==='owner'?'<label>権限<select name="role"><option value="user"'+(x.role==='user'?' selected':'')+'>user</option><option value="admin"'+(x.role==='admin'?' selected':'')+'>admin</option><option value="owner"'+(x.role==='owner'?' selected':'')+'>owner</option></select></label>':'',dialog=formDialog({title:'ユーザーを編集',description:x.email+' / '+x.id,fields:'<label>表示名<input name="displayName" required maxlength="200" value="'+esc(x.display_name)+'" autofocus></label>'+roleField+'<div class="wide notice warning" data-role-warning hidden></div>',submitLabel:'変更を保存',successMessage:'ユーザーを更新しました。',onSubmit:f=>{const body={displayName:String(f.get('displayName'))};if(me.role==='owner')body.role=String(f.get('role'));return request('/users/'+x.id,{method:'PATCH',...jsonBody(body)})}}),role=dialog.querySelector('[name="role"]'),warning=dialog.querySelector('[data-role-warning]');if(role){role.onchange=()=>{const changed=role.value!==x.role;warning.hidden=!changed;warning.textContent=changed?'権限を '+x.role+' から '+role.value+' へ変更します。':''};role.onchange()}else warning.remove()});
  bindAction('[data-u-status]',b=>{const x=d.items.find(v=>v.id===b.dataset.uStatus),action=b.dataset.active==='true'?'disable':'enable',self=x.id===me.userId&&action==='disable',verb=action==='disable'?'無効化':'有効化';confirmDialog({title:'ユーザーを'+verb,description:x.display_name+' / '+x.email,summary:(self?'<div class="notice warning"><strong>自分自身を無効化します。</strong> 実行後はこの管理画面を利用できません。</div>':'')+'<p>対象ユーザーを'+verb+'します。</p>',submitLabel:verb,danger:action==='disable',successMessage:'ユーザー状態を変更しました。',onSubmit:()=>request('/users/'+x.id+'/'+action,{method:'POST',...jsonBody({})})})});
  bindAction('[data-u-unlink]',b=>{const x=d.items.find(v=>v.id===b.dataset.uUnlink),self=x.id===me.userId;formDialog({title:'Access連携を解除',description:x.display_name+' / '+x.email,fields:'<div class="wide notice warning"><strong>現在のCloudflare AccessユーザーIDとの連携を解除します。</strong> Access policyやAccess sessionは変更されません。次に同じメールの検証済みidentityで管理画面を開くと再連携されます。</div><label class="wide">解除理由<textarea name="reason" required minlength="1" maxlength="500" autofocus></textarea><small>JWT、OTP、APIキーなどの秘密値は入力しないでください。</small></label><label class="wide check"><input type="checkbox" name="confirm" required> 影響を確認し、Access連携を解除します</label>',submitLabel:'Access連携を解除',danger:true,successMessage:self?'連携を解除しました。Accessからログアウトします。':'Access連携を解除しました。',reload:!self,afterSuccess:self?()=>location.assign('/cdn-cgi/access/logout'):undefined,onSubmit:f=>request('/users/'+x.id+'/unlink-access-subject',{method:'POST',...jsonBody({reason:String(f.get('reason')).trim()})})})})
}

async function accounts(){
  const[a,u,k]=await Promise.all([request('/service-accounts'),request('/users'),request('/api-keys')]);
  const ownerOptions=u.items.filter(x=>x.status==='active').map(x=>'<option value="'+esc(x.id)+'">'+esc(x.display_name+' ('+x.email+')')+'</option>').join(''),typeOptions=(selected='')=>[['codex','Codex'],['claude-code','Claude Code'],['mcp','MCP'],['ci','CI'],['generic','汎用CLI']].map(([value,label])=>'<option value="'+value+'"'+(selected===value?' selected':'')+'>'+label+'</option>').join('');
  out.innerHTML=section('サービスアカウント','<div class="actions"><button id="account-create">サービスアカウントを作成</button></div>'+table(a.items,[['名前','name'],['種類','client_type'],['所有者','owner_user_id'],['状態','status']],x=>'<button class="secondary" data-a-detail="'+esc(x.id)+'">詳細</button><button class="secondary" data-a-edit="'+esc(x.id)+'">編集</button><a class="button secondary" href="/admin/api-keys/?account='+encodeURIComponent(x.id)+'">APIキーを追加</a><button class="secondary" data-a-status="'+esc(x.id)+'" data-active="'+(x.status==='active')+'">'+(x.status==='active'?'無効化':'有効化')+'</button>'+(x.status==='active'?'<button class="danger" data-a-delete="'+esc(x.id)+'">無効化＋全キー失効</button>':'')));
  document.querySelector('#account-create').onclick=()=>formDialog({title:'サービスアカウントを作成',fields:'<label>所有者<select name="ownerUserId" autofocus>'+ownerOptions+'</select></label><label>名前<input name="name" required maxlength="100"></label><label>種類<select name="clientType">'+typeOptions()+'</select></label>',submitLabel:'作成',successMessage:'サービスアカウントを作成しました。',onSubmit:f=>request('/service-accounts',{method:'POST',...jsonBody(Object.fromEntries(f))})});
  bindAction('[data-a-detail]',b=>{const x=a.items.find(v=>v.id===b.dataset.aDetail);details({...x,apiKeys:k.items.filter(v=>v.service_account_id===x.id)},'サービスアカウント詳細')});
  bindAction('[data-a-edit]',b=>{const x=a.items.find(v=>v.id===b.dataset.aEdit);formDialog({title:'サービスアカウントを編集',description:x.id,fields:'<label>名前<input name="name" required maxlength="100" value="'+esc(x.name)+'" autofocus></label><label>種類<select name="clientType">'+typeOptions(x.client_type)+'</select></label>',submitLabel:'変更を保存',successMessage:'サービスアカウントを更新しました。',onSubmit:f=>request('/service-accounts/'+x.id,{method:'PATCH',...jsonBody({name:f.get('name'),clientType:f.get('clientType')})})})});
  bindAction('[data-a-status]',b=>{const x=a.items.find(v=>v.id===b.dataset.aStatus),action=b.dataset.active==='true'?'disable':'enable',verb=action==='disable'?'無効化':'有効化';confirmDialog({title:'サービスアカウントを'+verb,description:x.name+' / '+x.id,summary:'<p>関連APIキーは失効しません。</p>',submitLabel:verb,danger:action==='disable',successMessage:'サービスアカウント状態を変更しました。',onSubmit:()=>request('/service-accounts/'+x.id+'/'+action,{method:'POST',...jsonBody({})})})});
  bindAction('[data-a-delete]',b=>{const x=a.items.find(v=>v.id===b.dataset.aDelete),count=k.items.filter(v=>v.service_account_id===x.id&&v.revoked_at===null).length;confirmDialog({title:'無効化して全キーを失効',description:x.name+' / '+x.id,summary:'<div class="notice warning"><strong>サービスアカウントを無効化し、有効なAPIキー '+count+'件をすべて失効します。</strong></div>',submitLabel:'無効化＋全キー失効',danger:true,successMessage:'無効化とキー失効を実行しました。',onSubmit:()=>request('/service-accounts/'+x.id,{method:'DELETE'})})})
}
`;
